import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

test('real Node launcher persists projects across independent processes without Python or context writes', t => {
  const dir = mkdtempSync(join(tmpdir(), 'mypi-cli-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const entry = fileURLToPath(new URL('../../src/cli/main.js', import.meta.url));
  const env = { PATH: '/work/tools', HOME: dir, MYPI_PI_CONTEXT: 'malformed-fresh-launch-handoff', XDG_STATE_HOME: join(dir, 'state') };
  const run = (...args: string[]) => {
    const result = spawnSync(process.execPath, [entry, ...args], { env, cwd: dir, encoding: 'utf8', timeout: 3000 });
    assert.ifError(result.error);
    assert.equal(result.signal, null);
    return result;
  };
  const messages = run('message', 'list', 'offline-native-id');
  assert.equal(messages.status, 0, messages.stderr);
  assert.deepEqual(JSON.parse(messages.stdout), { messages: [], issues: [], truncated: false });
  const sessions = run('session', 'list', '--all');
  assert.equal(sessions.status, 0, sessions.stderr);
  assert.deepEqual(JSON.parse(sessions.stdout), { sessions: [], issues: [], truncated: false });
  const missingControl = run('session', 'focus', '11111111-1111-4111-8111-111111111111', '--all');
  assert.equal(missingControl.status, 1);
  assert.deepEqual(JSON.parse(missingControl.stderr), { status: 'error', message: 'Cannot control session observation: missing' });
  assert.equal(missingControl.stdout, '');
  assert.equal(run('project', 'list').status, 1);
  assert.equal(existsSync(join(dir, 'state')), false);
  const init = run('db', 'init');
  assert.equal(init.status, 0, init.stderr);
  const filename = JSON.parse(init.stdout).database as string;
  const add = run('project', 'add', 'one/project', '--code', 'MP');
  assert.equal(add.status, 0, add.stderr);
  const project = JSON.parse(add.stdout).project;
  assert.equal(project.code, 'MP');
  const before = readFileSync(filename);
  const list = run('project', 'list');
  assert.equal(list.status, 0, list.stderr);
  assert.deepEqual(JSON.parse(list.stdout).projects, [project]);
  assert.deepEqual(readFileSync(filename), before);
  const duplicate = run('project', 'add', 'two/project', '--code', 'MP');
  assert.equal(duplicate.status, 1);
  assert.equal(JSON.parse(duplicate.stderr).status, 'error');
  assert.equal(duplicate.stdout, '');
  assert.equal(existsSync(join(dir, 'home')), false);
});
