import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync, symlinkSync, linkSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { state } from '../support/state.js';
import { createTaskWorktree, auditWorktree, taskRevision } from '../../src/infrastructure/git/task-worktree.js';
import { createPrivateGit, copyPrivateTree } from '../../src/infrastructure/git/private-git.js';

test('task worktree uses committed blobs, no checkout hook/filter, and rejects escaping links', t => {
  const { dir } = state(t), repo = join(dir, 'repo'), work = join(dir, 'work');
  mkdirSync(repo);
  const git = (...args: string[]) => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8', timeout: 2000 });
  git('init', '-q'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@invalid');
  writeFileSync(join(repo, 'file'), 'committed');
  writeFileSync(join(repo, '.gitattributes'), 'file filter=trap\n');
  git('add', 'file', '.gitattributes'); git('commit', '-qm', 'base');
  git('config', 'filter.trap.smudge', 'echo filter > ' + join(dir, 'filter-ran'));
  git('config', 'filter.trap.clean', 'echo filter > ' + join(dir, 'filter-ran'));
  const revision = taskRevision(repo), branch = 'mypi/MP-1-' + 'a'.repeat(32);
  writeFileSync(join(repo, '.git/hooks/post-checkout'), '#!/bin/sh\necho broken > ' + join(dir, 'hook-ran'), { mode: 0o755 });
  writeFileSync(join(repo, 'file'), 'uncommitted');
  createTaskWorktree(repo, work, revision, branch);
  assert.equal(readFileSync(join(work, 'file'), 'utf8'), 'committed');
  assert.equal(existsSync(join(dir, 'hook-ran')), false);
  assert.equal(existsSync(join(dir, 'filter-ran')), false);
  assert.equal(readFileSync(join(repo, 'file'), 'utf8'), 'uncommitted');
  const privateGit = join(dir, 'private-git');
  createPrivateGit(repo, privateGit, revision, branch);
  assert.equal(readFileSync(join(privateGit, 'shallow'), 'utf8'), revision + '\n');
  assert.equal(readFileSync(join(privateGit, 'HEAD'), 'utf8'), 'ref: refs/heads/' + branch + '\n');
  copyPrivateTree(privateGit, join(dir, 'copy'));
  symlinkSync('/etc/passwd', join(work, 'escape'));
  assert.throws(() => auditWorktree(work), /symlink/); unlinkSync(join(work, 'escape'));
  linkSync(join(repo, 'file'), join(work, 'linked'));
  assert.throws(() => auditWorktree(work), /hardlinks/);
  symlinkSync('/etc/passwd', join(privateGit, 'escape'));
  assert.throws(() => copyPrivateTree(privateGit, join(dir, 'unsafe-copy')), /unlinked/);
});
